### ISSUE TITLE
Issues from visual inspection of news articles

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/zeiss#126]
Reported by @sdmcraft 

1. Social icons look darker on Franklin - **Piyush** (Done via https://github.com/hlxsites/zeiss/pull/138) 
2. Extra underline below hero in Franklin - **Piyush** (Done via https://github.com/hlxsites/zeiss/pull/134)
3. Paragraph font is different (takes more space on Franklin) (Done via https://github.com/hlxsites/zeiss/pull/152)
4. Author missing on https://main--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/verkauf-von-zeiss-itrap (Tracked via #133 )
5. Collapse block is wider on Franklin - **Piyush** (Done via https://github.com/hlxsites/zeiss/pull/149)
6. Pressebilder section has text missing and other content differences (addressed in #140 )
7. Bottommost dark footer is thicker in Franklin - **Piyush** (Covered via https://github.com/hlxsites/zeiss/issues/146)
8. Single image appears as carousel. It should be an image with caption. **David B** Covered via #156 and updated worddocs.
9. Contact is shifted too much to left - **Piyush** (Done via https://github.com/hlxsites/zeiss/pull/139)

**Comment by tmaret** [comment]
10. space smaller on www.zeiss.de

<img width="1904" alt="Screenshot 2023-04-20 at 15 04 18" src="https://user-images.githubusercontent.com/1628648/233384463-e6e78960-75b4-46ec-8f3f-0b7c85758e15.png">

**Comment by tmaret** [comment]
11. Uber Zeiss section layout significantly different than on www.zeiss.de

![Screenshot 2023-04-20 at 15 10 46](https://user-images.githubusercontent.com/1628648/233384893-07208f03-56d7-40c2-9a1c-64e7362e36b9.png)

![Screenshot 2023-04-20 at 15 10 54](https://user-images.githubusercontent.com/1628648/233384932-32300d02-58cc-4a84-a4e2-9262960ce7e4.png)

**Comment by tmaret** [comment]
12. Weiter article reading duration is incomplete and lowercase

![Screenshot 2023-04-20 at 15 15 59](https://user-images.githubusercontent.com/1628648/233385388-66d7c043-8625-49e3-b1ca-93b6916c4c9f.png)
![Screenshot 2023-04-20 at 15 16 58](https://user-images.githubusercontent.com/1628648/233385398-04ce344d-cb00-4535-8712-dbac52ad99da.png)

**Comment by tmaret** [comment]
13. Footer language chooser layout is broken

![Screenshot 2023-04-20 at 15 18 13](https://user-images.githubusercontent.com/1628648/233385612-fe8c6595-22a8-4524-815d-090b56aacb7d.png)
![Screenshot 2023-04-20 at 15 19 02](https://user-images.githubusercontent.com/1628648/233385614-07dd00c2-533e-4f92-8373-f37b402ce2de.png)

**Comment by alinarublea** [comment]
> 4\. https://main--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/verkauf-von-zeiss-itrap

I can take this one cc: @sdmcraft

**Comment by alinarublea** [comment]
1. Pressekontact is not alligned 
<img width="1331" alt="Screenshot 2023-04-20 at 19 50 38" src="https://user-images.githubusercontent.com/3886442/233434996-93bd9694-5a58-4676-bc53-2128acbd2726.png">
<img width="1003" alt="Screenshot 2023-04-20 at 19 50 52" src="https://user-images.githubusercontent.com/3886442/233435019-7c62fa34-007a-4324-9351-1edfde5348f3.png">

2. Missing footer for 2023 press releases

3. Image and text not properly formated in https://main--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/2023/zeiss-als-ehrenamtsfreundlicher-arbeitgeber-ausgezeichnet

<img width="1001" alt="Screenshot 2023-04-20 at 20 03 00" src="https://user-images.githubusercontent.com/3886442/233437503-b8bd295f-25ff-485b-9c06-061508cf538b.png">

<img width="1400" alt="Screenshot 2023-04-20 at 20 03 10" src="https://user-images.githubusercontent.com/3886442/233437514-bc0a270f-f9a8-42f9-a753-bfd16bf9e146.png">
4.

**Comment by bosschaert** [comment]
I'm happy to help with this one, but there are a lot of items here and some have the same number.

I'll start at the bottom and will look at:

7. Image and text not properly styled in https://main--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/ausgezeichnete-ausbildung-bei-zeiss

**Comment by alinarublea** [comment]
> I'm happy to help with this one, but there are a lot of items here and some have the same number.
> 
> I'll start at the bottom and will look at:
> 
> 7. Image and text not properly styled in https://main--zeiss--hlxsites.hlx.page/de/semiconductor-manufacturing-technology/news-und-events/smt-pressemeldung/ausgezeichnete-ausbildung-bei-zeiss

Yes, I renumbered this one to 23, you can update the comment

**Comment by sdmcraft** [comment]
25. [Mehr unter www.zeiss.de](https://issue-11--zeiss--hlxsites.hlx.page/) link is incorrect in collapse block.

**Comment by jindaliiita** [comment]
Taking these 2 
``

> Reported by @sdmcraft
> 
> 1. Social icons look darker on Franklin
> 2. Extra underline below hero in Franklin

**Comment by sdmcraft** [comment]
@jindaliiita , I think 21 and 23 in the list above have been addressed. Could you please confirm and mark them as resolved referencing the ticket which fixed them?

**Comment by jindaliiita** [comment]
> @jindaliiita , I think 21 and 23 in the list above have been addressed. Could you please confirm and mark them as resolved referencing the ticket which fixed them?

Not Completely solved as copyright part and heading part are being tracked via https://github.com/hlxsites/zeiss/pull/132.
Rest all are done

**Comment by jindaliiita** [comment]
25. Contact Section missing on https://main--zeiss--hlxsites.hlx.page/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases-21-Apr-23-bkp/intels-preferred-quality-supplier-award-2020.

Seems to be issue with content https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B2FA23D80-564D-4A13-AC82-C2D08BDB12E0%7D&file=intels-preferred-quality-supplier-award-2020.docx&action=default&mobileredirect=true
<img width="1728" alt="Screenshot 2023-04-24 at 5 28 40 PM" src="https://user-images.githubusercontent.com/12638407/233990282-7d99529c-0526-4d49-b721-9cbfa7527d3c.png">

<img width="1728" alt="Screenshot 2023-04-24 at 5 30 50 PM" src="https://user-images.githubusercontent.com/12638407/233990266-000cf4b6-cbab-47ad-b740-7714364c7a9e.png">

**Comment by sdmcraft** [comment]
Closing this as all the points listed here have a tracking link associated with them and can be tracked individually.
